#!/bin/bash
cython --embed conv_gauss.pyx

gcc $CFLAGS -I/usr/include/python3.4 conv_gauss.c -shared -pthread -fPIC -fwrapv -O2 -Wall -fno-strict-aliasing -o conv_gauss.so
sudo cp conv_gauss.so /usr/local/lib/python3/dist-packages/morse/sensors/conv_gauss.so

#$(pkg-config python --cflags) 
